#ifndef CONST_H
#define CONST_H

#define MAX_LINE_LENGTH 80
#define MAX_MACROS_LINES 10
#define MAX_LINE_OUTPUT 16
#define MAX_LABEL_LENGTH 31
#define SYMBOL_TABLE_LENGTH 6
#define SYMBOL_START_POINT 100
#define MIN_COMMAND_LENGTH 3
#define MAX_COMMAND_LENGTH 4
#define REGISTER_NAME_LENGTH 2

#endif
